<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\{
    Product, Category, ProductChannel, PharmaceuticalForm, 
    ProductType, Molecule, Laboratory, CommercialName, 
    UnitOfMeasure, Business
};

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $businessId = 1; // Asegúrate de que este ID de negocio exista

        // Unidades de medida
        $unidad = UnitOfMeasure::firstOrCreate(
            ['name' => 'Unidad', 'business_id' => $businessId],
            ['code' => 'UND', 'conversion_factor' => 1]
        );

        $caja = UnitOfMeasure::firstOrCreate(
            ['name' => 'Caja', 'business_id' => $businessId],
            ['code' => 'CJA', 'conversion_factor' => 1]
        );

        $products = [
            // ==================== ANALGÉSICOS Y ANTIINFLAMATORIOS ====================
            [
                'sku' => 'MED-100092',
                'name' => 'ACETAMINOFEN 500MG TABLETA CAJA X 100',
                'price' => 8500,
                'tax_rate' => 0,
                'category' => 'ANALGESICOS Y ANTIPIRETICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'MK',
                'molecule' => 'ACETAMINOFEN',
                'concentration' => '500MG',
                'form' => 'TABLETA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'ACETAMINOFEN MK',
                'cum' => '19900012-1',
                'invima' => '2018M-0009876',
                'atc_code' => 'N02BE01',
                'barcode' => '7702057010010',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 50,
            ],
            [
                'sku' => 'MED-156789',
                'name' => 'IBUPROFENO 400MG CAPSULA BLANDA CAJA X 10',
                'price' => 12500,
                'tax_rate' => 0,
                'category' => 'ANALGESICOS Y ANTIPIRETICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'PFIZER',
                'molecule' => 'IBUPROFENO',
                'concentration' => '400MG',
                'form' => 'CAPSULA BLANDA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'ADVIL',
                'cum' => '20054321-0',
                'invima' => '2020M-0005566',
                'atc_code' => 'M01AE01',
                'barcode' => '7702057010027',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 30,
            ],
            [
                'sku' => 'MED-100093',
                'name' => 'DICLOFENACO SODICO 50MG TABLETA CAJA X 30',
                'price' => 15800,
                'tax_rate' => 0,
                'category' => 'ANALGESICOS Y ANTIPIRETICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'GENFAR',
                'molecule' => 'DICLOFENACO',
                'concentration' => '50MG',
                'form' => 'TABLETA',
                'channel' => 'GENERICO',
                'commercial_name' => 'DICLOFENACO GENFAR',
                'cum' => '19945679-1',
                'invima' => '2019M-0004321',
                'atc_code' => 'M01AB05',
                'barcode' => '7702057010034',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 40,
            ],
            [
                'sku' => 'MED-100094',
                'name' => 'NAPROXENO 250MG TABLETA CAJA X 20',
                'price' => 9200,
                'tax_rate' => 0,
                'category' => 'ANALGESICOS Y ANTIPIRETICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'LA SANTE',
                'molecule' => 'NAPROXENO',
                'concentration' => '250MG',
                'form' => 'TABLETA',
                'channel' => 'GENERICO',
                'commercial_name' => 'NAPROXENO',
                'cum' => '19956789-2',
                'invima' => '2018M-0006543',
                'atc_code' => 'M01AE02',
                'barcode' => '7702057010041',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 35,
            ],

            // ==================== ANTIBIÓTICOS ====================
            [
                'sku' => 'MED-105543',
                'name' => 'AMOXICILINA 500MG CAPSULA CAJA X 50',
                'price' => 18500,
                'tax_rate' => 0,
                'category' => 'ANTIBIOTICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'GENFAR',
                'molecule' => 'AMOXICILINA',
                'concentration' => '500MG',
                'form' => 'CAPSULA',
                'channel' => 'GENERICO',
                'commercial_name' => 'AMOXICILINA GENFAR',
                'cum' => '19945678-3',
                'invima' => '2020M-0005432',
                'atc_code' => 'J01CA04',
                'barcode' => '7702057020010',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 60,
            ],
            [
                'sku' => 'MED-105544',
                'name' => 'AMOXICILINA + ACIDO CLAVULANICO 875/125MG TABLETA CAJA X 14',
                'price' => 45000,
                'tax_rate' => 0,
                'category' => 'ANTIBIOTICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'MK',
                'molecule' => 'AMOXICILINA+ACIDO CLAVULANICO',
                'concentration' => '875MG/125MG',
                'form' => 'TABLETA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'AUGMENTIN',
                'cum' => '19967890-4',
                'invima' => '2019M-0007654',
                'atc_code' => 'J01CR02',
                'barcode' => '7702057020027',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 25,
            ],
            [
                'sku' => 'MED-105545',
                'name' => 'AZITROMICINA 500MG TABLETA CAJA X 3',
                'price' => 12800,
                'tax_rate' => 0,
                'category' => 'ANTIBIOTICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'PFIZER',
                'molecule' => 'AZITROMICINA',
                'concentration' => '500MG',
                'form' => 'TABLETA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'ZITROMAX',
                'cum' => '19978901-5',
                'invima' => '2018M-0008765',
                'atc_code' => 'J01FA10',
                'barcode' => '7702057020034',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 40,
            ],
            [
                'sku' => 'MED-105546',
                'name' => 'CEFALEXINA 500MG CAPSULA CAJA X 30',
                'price' => 22500,
                'tax_rate' => 0,
                'category' => 'ANTIBIOTICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'GENFAR',
                'molecule' => 'CEFALEXINA',
                'concentration' => '500MG',
                'form' => 'CAPSULA',
                'channel' => 'GENERICO',
                'commercial_name' => 'CEFALEXINA',
                'cum' => '19989012-6',
                'invima' => '2020M-0009876',
                'atc_code' => 'J01DB01',
                'barcode' => '7702057020041',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 35,
            ],

            // ==================== ANTIHIPERTENSIVOS ====================
            [
                'sku' => 'MED-108900',
                'name' => 'LOSARTAN 50MG TABLETA CAJA X 30',
                'price' => 16500,
                'tax_rate' => 0,
                'category' => 'ANTIHIPERTENSIVOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'MK',
                'molecule' => 'LOSARTAN',
                'concentration' => '50MG',
                'form' => 'TABLETA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'LOSARTAN MK',
                'cum' => '19991234-5',
                'invima' => '2018M-0001122',
                'atc_code' => 'C09CA01',
                'barcode' => '7702057030010',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 50,
            ],
            [
                'sku' => 'MED-108901',
                'name' => 'ENALAPRIL 10MG TABLETA CAJA X 30',
                'price' => 8900,
                'tax_rate' => 0,
                'category' => 'ANTIHIPERTENSIVOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'GENFAR',
                'molecule' => 'ENALAPRIL',
                'concentration' => '10MG',
                'form' => 'TABLETA',
                'channel' => 'GENERICO',
                'commercial_name' => 'ENALAPRIL',
                'cum' => '19992345-6',
                'invima' => '2019M-0002233',
                'atc_code' => 'C09AA02',
                'barcode' => '7702057030027',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 60,
            ],
            [
                'sku' => 'MED-108902',
                'name' => 'AMLODIPINO 5MG TABLETA CAJA X 30',
                'price' => 7500,
                'tax_rate' => 0,
                'category' => 'ANTIHIPERTENSIVOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'LA SANTE',
                'molecule' => 'AMLODIPINO',
                'concentration' => '5MG',
                'form' => 'TABLETA',
                'channel' => 'GENERICO',
                'commercial_name' => 'AMLODIPINO',
                'cum' => '19993456-7',
                'invima' => '2018M-0003344',
                'atc_code' => 'C08CA01',
                'barcode' => '7702057030034',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 55,
            ],

            // ==================== ANTIULCEROSOS Y DIGESTIVOS ====================
            [
                'sku' => 'MED-112233',
                'name' => 'OMEPRAZOL 20MG CAPSULA CAJA X 30',
                'price' => 12300,
                'tax_rate' => 0,
                'category' => 'ANTIULCEROSOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'LA SANTE',
                'molecule' => 'OMEPRAZOL',
                'concentration' => '20MG',
                'form' => 'CAPSULA',
                'channel' => 'GENERICO',
                'commercial_name' => 'OMEPRAZOL',
                'cum' => '19967890-2',
                'invima' => '2019M-0003344',
                'atc_code' => 'A02BC01',
                'barcode' => '7702057040010',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 45,
            ],
            [
                'sku' => 'MED-112234',
                'name' => 'RANITIDINA 150MG TABLETA CAJA X 20',
                'price' => 9800,
                'tax_rate' => 0,
                'category' => 'ANTIULCEROSOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'GENFAR',
                'molecule' => 'RANITIDINA',
                'concentration' => '150MG',
                'form' => 'TABLETA',
                'channel' => 'GENERICO',
                'commercial_name' => 'RANITIDINA',
                'cum' => '19968901-3',
                'invima' => '2018M-0004455',
                'atc_code' => 'A02BA02',
                'barcode' => '7702057040027',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 40,
            ],

            // ==================== ANTIDIABÉTICOS ====================
            [
                'sku' => 'MED-145230',
                'name' => 'INSULINA GLARGINA 100UI/ML PLUMA PRECARGADA X 3ML',
                'price' => 185000,
                'tax_rate' => 0,
                'category' => 'ANTIDIABETICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'SANOFI',
                'molecule' => 'INSULINA GLARGINA',
                'concentration' => '100UI/ML',
                'form' => 'INYECTABLE',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'LANTUS',
                'cum' => '20019876-1',
                'invima' => '2021M-0019876',
                'atc_code' => 'A10AE04',
                'barcode' => '7702057050010',
                'controlled' => false,
                'cold_chain' => true, // Cadena de frío
                'stock_minimo' => 15,
            ],
            [
                'sku' => 'MED-145231',
                'name' => 'METFORMINA 850MG TABLETA CAJA X 30',
                'price' => 8500,
                'tax_rate' => 0,
                'category' => 'ANTIDIABETICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'GENFAR',
                'molecule' => 'METFORMINA',
                'concentration' => '850MG',
                'form' => 'TABLETA',
                'channel' => 'GENERICO',
                'commercial_name' => 'METFORMINA',
                'cum' => '20020987-2',
                'invima' => '2019M-0020987',
                'atc_code' => 'A10BA02',
                'barcode' => '7702057050027',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 50,
            ],
            [
                'sku' => 'MED-145232',
                'name' => 'GLIBENCLAMIDA 5MG TABLETA CAJA X 30',
                'price' => 6800,
                'tax_rate' => 0,
                'category' => 'ANTIDIABETICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'MK',
                'molecule' => 'GLIBENCLAMIDA',
                'concentration' => '5MG',
                'form' => 'TABLETA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'GLIBENCLAMIDA MK',
                'cum' => '20021098-3',
                'invima' => '2018M-0021098',
                'atc_code' => 'A10BB01',
                'barcode' => '7702057050034',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 45,
            ],

            // ==================== PSICOLÉPTICOS (CONTROLADOS) ====================
            [
                'sku' => 'MED-129504',
                'name' => 'ZOLPIDEM 10MG TABLETA CAJA X 30',
                'price' => 45000,
                'tax_rate' => 0,
                'category' => 'PSICOLEPTICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'HUMAX',
                'molecule' => 'ZOLPIDEM',
                'concentration' => '10MG',
                'form' => 'TABLETA',
                'channel' => 'INSTITUCIONAL',
                'commercial_name' => 'ZOLPIDEM',
                'cum' => '19982431-2',
                'invima' => '2022M-0007701-R1',
                'atc_code' => 'N05CF02',
                'barcode' => '7702057060010',
                'controlled' => true, // Controlado
                'cold_chain' => false,
                'stock_minimo' => 10,
            ],
            [
                'sku' => 'MED-102247',
                'name' => 'ZOPICLONA 7.5MG TABLETA CAJA X 10',
                'price' => 28500,
                'tax_rate' => 0,
                'category' => 'PSICOLEPTICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'GENFAR',
                'molecule' => 'ZOPICLONA',
                'concentration' => '7.5MG',
                'form' => 'TABLETA',
                'channel' => 'INSTITUCIONAL',
                'commercial_name' => 'ZOPICLONA GENFAR',
                'cum' => '19942514-1',
                'invima' => '2019M-0003170-R2',
                'atc_code' => 'N05CF01',
                'barcode' => '7702057060027',
                'controlled' => true,
                'cold_chain' => false,
                'stock_minimo' => 10,
            ],
            [
                'sku' => 'MED-129505',
                'name' => 'ALPRAZOLAM 0.5MG TABLETA CAJA X 30',
                'price' => 18500,
                'tax_rate' => 0,
                'category' => 'PSICOLEPTICOS',
                'type' => 'MEDICAMENTO',
                'lab' => 'PFIZER',
                'molecule' => 'ALPRAZOLAM',
                'concentration' => '0.5MG',
                'form' => 'TABLETA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'XANAX',
                'cum' => '19983542-3',
                'invima' => '2020M-0008812-R1',
                'atc_code' => 'N05BA12',
                'barcode' => '7702057060034',
                'controlled' => true,
                'cold_chain' => false,
                'stock_minimo' => 15,
            ],

            // ==================== EXPECTORANTES Y ANTITUSIVOS ====================
            [
                'sku' => 'MED-132126',
                'name' => 'TUKOL D JARABE FRASCO X 125ML',
                'price' => 18900,
                'tax_rate' => 19, // Tiene IVA
                'category' => 'EXPECTORANTES',
                'type' => 'MEDICAMENTO',
                'lab' => 'GENOMMA LAB',
                'molecule' => 'BROMHEXINA+GUAYACOLATO',
                'concentration' => '4MG/100MG',
                'form' => 'JARABE',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'TUKOL D',
                'cum' => '20056789-1',
                'invima' => '2019M-0012345',
                'atc_code' => 'R05CB02',
                'barcode' => '7702057070010',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 25,
            ],
            [
                'sku' => 'MED-132127',
                'name' => 'AMBROXOL 30MG/5ML JARABE FRASCO X 120ML',
                'price' => 12500,
                'tax_rate' => 0,
                'category' => 'EXPECTORANTES',
                'type' => 'MEDICAMENTO',
                'lab' => 'GENFAR',
                'molecule' => 'AMBROXOL',
                'concentration' => '30MG/5ML',
                'form' => 'JARABE',
                'channel' => 'GENERICO',
                'commercial_name' => 'AMBROXOL',
                'cum' => '20057890-2',
                'invima' => '2018M-0013456',
                'atc_code' => 'R05CB06',
                'barcode' => '7702057070027',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 30,
            ],

            // ==================== HORMONAS Y REGULADORES ====================
            [
                'sku' => 'MED-134696',
                'name' => 'SINOVUL (ETINILESTRADIOL+LEVONORGESTREL) BLISTER X 21 TABLETAS',
                'price' => 8500,
                'tax_rate' => 0,
                'category' => 'HORMONAS Y REGULADORES',
                'type' => 'MEDICAMENTO',
                'lab' => 'LAFRANCOL',
                'molecule' => 'ETINILESTRADIOL+LEVONORGESTREL',
                'concentration' => '0.03MG/0.15MG',
                'form' => 'TABLETA',
                'channel' => 'INSTITUCIONAL',
                'commercial_name' => 'SINOVUL',
                'cum' => '19981474-2',
                'invima' => '2018M-0007478-R1',
                'atc_code' => 'G03AA07',
                'barcode' => '7702057080010',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 40,
            ],

            // ==================== DISPOSITIVOS MÉDICOS ====================
            [
                'sku' => 'DM-319995',
                'name' => 'JABON QUIRURGICO EZ SCRUB CAJA X 4 UNIDADES',
                'price' => 85000,
                'tax_rate' => 19,
                'category' => 'MEDICO QUIRURGICO',
                'type' => 'DISPOSITIVO MEDICO',
                'lab' => 'BD',
                'molecule' => null,
                'concentration' => null,
                'form' => 'JABON',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'EZ SCRUB',
                'cum' => null,
                'invima' => '2021DM-0007613-R1',
                'atc_code' => null,
                'barcode' => '7702057100010',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 20,
            ],
            [
                'sku' => 'DM-111920',
                'name' => 'VENDA SINTETICA 3X4YDS BLANCO',
                'price' => 12500,
                'tax_rate' => 19,
                'category' => 'VENDAS',
                'type' => 'DISPOSITIVO MEDICO',
                'lab' => 'BSN MEDICAL',
                'molecule' => null,
                'concentration' => null,
                'form' => 'ROLLO',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'DELTA LITE PLUS',
                'cum' => null,
                'invima' => '2018DM-0003337-R1',
                'atc_code' => null,
                'barcode' => '7702057100027',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 50,
            ],
            [
                'sku' => 'DM-200150',
                'name' => 'JERINGA 5ML 21G X 1 1/2 PULGADAS',
                'price' => 450,
                'tax_rate' => 19,
                'category' => 'INYECCION',
                'type' => 'DISPOSITIVO MEDICO',
                'lab' => 'NIPRO',
                'molecule' => null,
                'concentration' => null,
                'form' => 'UNIDAD',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'JERINGA NIPRO',
                'cum' => null,
                'invima' => '2017DM-0016789',
                'atc_code' => null,
                'barcode' => '7702057100034',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 500,
            ],
            [
                'sku' => 'DM-200151',
                'name' => 'GUANTES EXAMEN NITRILO TALLA M CAJA X 100',
                'price' => 28500,
                'tax_rate' => 19,
                'category' => 'PROTECCION',
                'type' => 'DISPOSITIVO MEDICO',
                'lab' => 'SUPERIOR',
                'molecule' => null,
                'concentration' => null,
                'form' => 'CAJA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'GUANTES NITRILO',
                'cum' => null,
                'invima' => '2019DM-0023456',
                'atc_code' => null,
                'barcode' => '7702057100041',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 100,
            ],
            [
                'sku' => 'DM-200152',
                'name' => 'TAPABOCAS QUIRURGICO CAJA X 50',
                'price' => 15000,
                'tax_rate' => 19,
                'category' => 'PROTECCION',
                'type' => 'DISPOSITIVO MEDICO',
                'lab' => '3M',
                'molecule' => null,
                'concentration' => null,
                'form' => 'CAJA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'TAPABOCAS 3M',
                'cum' => null,
                'invima' => '2020DM-0034567',
                'atc_code' => null,
                'barcode' => '7702057100058',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 200,
            ],
            [
                'sku' => 'DM-200155',
                'name' => 'ALGODON LAMINADO 500GR',
                'price' => 18500,
                'tax_rate' => 19,
                'category' => 'CURACION',
                'type' => 'DISPOSITIVO MEDICO',
                'lab' => 'JGB',
                'molecule' => null,
                'concentration' => null,
                'form' => 'BOLSA',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'ALGODON JGB',
                'cum' => null,
                'invima' => '2015DM-0011223',
                'atc_code' => null,
                'barcode' => '7702057100065',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 60,
            ],
            [
                'sku' => 'DM-200156',
                'name' => 'TERMOMETRO DIGITAL PUNTA FLEXIBLE',
                'price' => 12500,
                'tax_rate' => 19,
                'category' => 'DIAGNOSTICO',
                'type' => 'EQUIPO BIOMEDICO',
                'lab' => 'GMD',
                'molecule' => null,
                'concentration' => null,
                'form' => 'UNIDAD',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'TERMOMETRO GMD',
                'cum' => null,
                'invima' => '2021EBC-0004567',
                'atc_code' => null,
                'barcode' => '7702057100072',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 30,
            ],
            [
                'sku' => 'DM-200157',
                'name' => 'BAJALENGUAS MADERA PAQUETE X 20',
                'price' => 2500,
                'tax_rate' => 19,
                'category' => 'CONSULTORIO',
                'type' => 'DISPOSITIVO MEDICO',
                'lab' => 'GENERICO',
                'molecule' => null,
                'concentration' => null,
                'form' => 'PAQUETE',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'BAJALENGUAS',
                'cum' => null,
                'invima' => '2010DM-0009988',
                'atc_code' => null,
                'barcode' => '7702057100089',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 100,
            ],
            [
                'sku' => 'DM-200158',
                'name' => 'MICROPORE BLANCO 1/2 X 10 YDS',
                'price' => 4500,
                'tax_rate' => 19,
                'category' => 'CURACION',
                'type' => 'DISPOSITIVO MEDICO',
                'lab' => '3M',
                'molecule' => null,
                'concentration' => null,
                'form' => 'ROLLO',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'MICROPORE',
                'cum' => null,
                'invima' => '2016DM-0014567',
                'atc_code' => null,
                'barcode' => '7702057100096',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 80,
            ],
            [
                'sku' => 'DM-200159',
                'name' => 'GASAS ESTERILES 10X10CM PAQUETE X 10',
                'price' => 3800,
                'tax_rate' => 19,
                'category' => 'CURACION',
                'type' => 'DISPOSITIVO MEDICO',
                'lab' => 'JGB',
                'molecule' => null,
                'concentration' => null,
                'form' => 'PAQUETE',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'GASAS JGB',
                'cum' => null,
                'invima' => '2017DM-0015678',
                'atc_code' => null,
                'barcode' => '7702057100102',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 150,
            ],

            // ==================== COSMÉTICOS Y DERMATOLÓGICOS ====================
            [
                'sku' => 'COSM-319033',
                'name' => 'ACEITE DE DUCHA TOP FRASCO X 200ML (EUCERIN PH5)',
                'price' => 45000,
                'tax_rate' => 19,
                'category' => 'DERMATOLOGICOS',
                'type' => 'COSMETICO',
                'lab' => 'BEIERSDORF',
                'molecule' => null,
                'concentration' => null,
                'form' => 'FRASCO',
                'channel' => 'COMERCIAL',
                'commercial_name' => 'EUCERIN',
                'cum' => null,
                'invima' => 'NSOC12345-12CO',
                'atc_code' => null,
                'barcode' => '7702057200010',
                'controlled' => false,
                'cold_chain' => false,
                'stock_minimo' => 20,
            ],
        ];

        echo "🌱 Iniciando seeder de productos...\n";
        $count = 0;

        foreach ($products as $p) {
            // Crear o encontrar relaciones
            // NOTA: Solo 'categories' tiene business_id, las demás tablas son compartidas
            $cat = Category::firstOrCreate(
                ['name' => $p['category'], 'business_id' => $businessId]
            );
            
            $type = ProductType::firstOrCreate(
                ['name' => $p['type']]
            );
            
            $lab = Laboratory::firstOrCreate(
                ['name' => $p['lab']]
            );
            
            $form = PharmaceuticalForm::firstOrCreate(
                ['name' => $p['form']]
            );
            
            $channel = ProductChannel::firstOrCreate(
                ['name' => $p['channel']]
            );
            
            $molecule = null;
            if ($p['molecule']) {
                $molecule = Molecule::firstOrCreate(
                    ['name' => $p['molecule']]
                );
            }

            $commercial = null;
            if ($p['commercial_name']) {
                $commercial = CommercialName::firstOrCreate(
                    ['name' => $p['commercial_name']]
                );
            }

            // Crear Producto
            Product::create([
                'business_id' => $businessId,
                'name' => $p['name'],
                'sku' => $p['sku'],
                'tax_rate' => $p['tax_rate'],
                'has_tax' => $p['tax_rate'] > 0,
                'category_id' => $cat->id,
                'product_type_id' => $type->id,
                'laboratory_id' => $lab->id,
                'pharmaceutical_form_id' => $form->id,
                'product_channel_id' => $channel->id,
                'molecule_id' => $molecule ? $molecule->id : null,
                'commercial_name_id' => $commercial ? $commercial->id : null,
                'unit_of_measure_id' => $unidad->id,
                'concentration' => $p['concentration'] ?? null,
                'cum' => $p['cum'],
                'invima_registration' => $p['invima'],
                'atc_code' => $p['atc_code'] ?? null,
                'barcode' => $p['barcode'] ?? null,
                'controlled' => $p['controlled'],
                'cold_chain' => $p['cold_chain'],
                'stock_minimo' => $p['stock_minimo'] ?? 0,
                'is_active' => true,
            ]);

            $count++;
            echo "✓ Producto creado: {$p['name']}\n";
        }

        echo "\n✅ Seeder completado: {$count} productos creados exitosamente.\n";
    }
}